services:
  web:
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=sqlite3:storage/db/development.sqlite3
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle
      - node_modules:/rails/node_modules
      - rails_tmp:/rails/tmp
      - rails_log:/rails/log
    ports:
      - "3000:80"
    command: ["bin/dev"]
    stdin_open: true
    tty: true

  redis:
    ports:
      - "6379:6379"

volumes:
  bundle_cache:
  node_modules: